# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d92acdc0fd62890526feeb0359e231c95d12275b51beb93a9f1c8ce937618f690e32e0c7f993ee9fb28d974f944d192c037b13735aad2cb04f59117cb6c83bc

test:
  secret_key_base: 45f6cb25fd00ee5b58049c6f12923937a2fd378745e5593f136ab3a11223e1d123b845b79b1df613760073f7486588e34a7234dcb8c2a694c2727decf2cfd475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
